language: r

cache: packages

r:
  - oldrel
  - release

os:
    - linux
    - osx

before_install:
  - rm .Rprofile
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt install libgsl-dev; fi

addons:
  homebrew:
    packages:
      - gsl

r_packages:
    - rmarkdown

r_github_packages:
    - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - main

notifications:
    email:
      recipients:
          - {{ cookiecutter.email }}
      on_success: change
      on_failure: always
